---
# tasks file for docker
- name: create image docker
  docker_image: 
    name: projet-cd
    build:
     path: /var/lib/jenkins/workspace/projet-cd
     pull: no
    source: build
    state: present
    force_source: true
- name: run container docker
  docker_container:
    name: projetcd_container
    image: projet-cd:latest
    state: started
    recreate: true
    ports:
     - "4200:80"
